
export class QUOTEPOLICYINFORMATION{

    AGENTNUMBER: string;
    AGENTNAME: string;
    WEBACCOUNTNUMBER: string;
    WEBACCOUNTNAME: string;
    TRANSACTIONCODE: string;
    TRANSACTIONTYPE: string;
    QUOTEPOLICYNUMBER: string;
    EFFECTIVEDATE: number;
    ENDORSEMENTNUMBER: number;
    ENDORSEMENTDATE: number;
    RECORDTYPE: number;

}